# Generated by Django 4.2.6 on 2023-10-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbMoveInfo',
            fields=[
                ('move_id', models.AutoField(db_column='Move_ID', primary_key=True, serialize=False)),
                ('move_name', models.CharField(db_column='Move_Name', max_length=20)),
                ('move_type', models.IntegerField(db_column='Move_Type')),
                ('move_power', models.IntegerField(db_column='Move_Power')),
                ('accuracy', models.IntegerField(db_column='Accuracy')),
                ('is_zmove', models.BooleanField(db_column='Is_ZMove')),
            ],
            options={
                'db_table': 'tb_move_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbOrderColumn',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('season_id', models.IntegerField(db_column='Season_ID')),
                ('display_name', models.IntegerField(db_column='Display_Name')),
            ],
            options={
                'db_table': 'tb_order_column',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbOrderDetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('column_id', models.IntegerField(db_column='Column_ID')),
                ('card_id', models.IntegerField(db_column='Card_ID')),
                ('order_position', models.IntegerField(db_column='Order_Position')),
            ],
            options={
                'db_table': 'tb_order_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbCardInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('card_id', models.CharField(db_column='Card_ID', max_length=10)),
                ('season_id', models.IntegerField(blank=True, db_column='Season_ID', null=True)),
                ('energy', models.IntegerField(db_column='Energy')),
                ('star', models.IntegerField(blank=True, db_column='Star', null=True)),
                ('pm_name', models.CharField(db_column='PM_Name', max_length=50)),
                ('type1_id', models.IntegerField(db_column='Type1_ID')),
                ('type2_id', models.IntegerField(blank=True, db_column='Type2_ID', null=True)),
                ('hp', models.IntegerField(db_column='HP')),
                ('attack', models.IntegerField(db_column='Attack')),
                ('sp_attack', models.IntegerField(db_column='SP_Attack')),
                ('defense', models.IntegerField(db_column='Defense')),
                ('sp_defense', models.IntegerField(db_column='SP_Defense')),
                ('speed', models.IntegerField(db_column='Speed')),
                ('pm_id', models.IntegerField(db_column='PM_ID')),
                ('pm_form', models.CharField(blank=True, db_column='PM_Form', max_length=10, null=True)),
                ('sp_system', models.IntegerField(blank=True, db_column='SP_System', db_comment='1: Mega进化 2: Z招式 4: 合体 8: 双重冲击 16: 连续冲击', null=True)),
                ('move1_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Move1_ID', to='card_admin.tbmoveinfo')),
                ('move2_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Move2_ID', to='card_admin.tbmoveinfo')),
                ('zmove_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ZMove_ID', to='card_admin.tbmoveinfo')),
            ],
            options={
                'db_table': 'tb_card_info',
                'managed': True,
            },
        ),
    ]
