# Generated by Django 4.2.6 on 2023-10-19 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tborderdetail',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Card_ID', to='card_admin.tbcardinfo'),
        ),
        migrations.AlterField(
            model_name='tborderdetail',
            name='column_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Column_ID', to='card_admin.tbordercolumn'),
        ),
    ]
