# Generated by Django 4.2.6 on 2023-10-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_admin', '0002_alter_tborderdetail_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcardinfo',
            name='move2_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Move2_ID', to='card_admin.tbmoveinfo'),
        ),
        migrations.AlterField(
            model_name='tbcardinfo',
            name='zmove_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ZMove_ID', to='card_admin.tbmoveinfo'),
        ),
    ]
