# Generated by Django 4.2.6 on 2023-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_admin', '0003_alter_tbcardinfo_move2_id_alter_tbcardinfo_zmove_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcardinfo',
            name='type1_id',
        ),
        migrations.RemoveField(
            model_name='tbcardinfo',
            name='type2_id',
        ),
        migrations.AddField(
            model_name='tbcardinfo',
            name='type1',
            field=models.CharField(db_column='Type1', default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbcardinfo',
            name='type2',
            field=models.CharField(blank=True, db_column='Type2', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbmoveinfo',
            name='move_type',
            field=models.CharField(db_column='Move_Type', max_length=10),
        ),
    ]
