# Generated by Django 4.2.6 on 2023-10-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_admin', '0008_remove_tbcardinfo_pm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcardinfo',
            name='pm_form',
        ),
        migrations.RemoveField(
            model_name='tbcardinfo',
            name='pm_name',
        ),
        migrations.RemoveField(
            model_name='tbcardinfo',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='tbcardinfo',
            name='type2',
        ),
        migrations.AlterField(
            model_name='tbcardinfo',
            name='pm_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PM', to='card_admin.tbpminfo'),
        ),
    ]
