# Generated by Django 4.2.6 on 2023-10-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_admin', '0010_alter_tbpminfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbmoveinfo',
            unique_together={('move_name', 'move_power')},
        ),
        migrations.AlterUniqueTogether(
            name='tbordercolumn',
            unique_together={('season_id', 'display_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tborderdetail',
            unique_together={('column_id', 'order_position')},
        ),
    ]
